#!/bin/bash

# comment
COMM="echo comment: "
#COMM=":"
NOTE="echo note: "
#NOTE=":"
DEBUG="echo debug: "
DEBUG=":"

outputfolder=$1
Msgfile=`realpath $2`
Csvfile=`realpath $3`
Csvfilesnew="new-$$.csv"
DATETIME=`date +"%Y%m%d%H%M"`
TEMPFILE="/tmp/$DATETIME-$$"


declare -A USAGE
USAGE[general]="Usage: $0 [outputfolder (in general .)] $outputfolder [Msgfile] $Msgfile [Csvfile] $Csvfile"
USAGE[action]="1st column is unique key in [Csvsfile] $Csvfile, fieldseparator is TAB or ;, subfolder [files] in [outputfolder] $outputfolder will be created"
USAGE[outputfolder]="$outputfolder not exists"
USAGE[Csvfile]="$Csvfile not exists"
USAGE[TAB]="TAB not fieldseparator"
USAGE[Msgfile]="$Msgfile not exists"
USAGE[para4]="4th parameter is empty, so we ask : continue with Enter, cancel with CTRL+C"

$NOTE ${USAGE[general]}
$NOTE ${USAGE[action]}

if [ $# -lt 3 ]
then
 exit 1
fi

$COMM Test $outputfolder
if [ ! -d $outputfolder ]
then
 $NOTE ${USAGE[outputfolder]}
 exit 2
fi

$COMM Test $Csvfile
if [ ! -e $Csvfile ]
then
 $NOTE ${USAGE[Csvfile]}
 exit 3
fi

$COMM Test is TAB fieldseparator of $Csvfile
columns=`head -1 $Csvfile`
numberofcolumns=`echo $columns|awk -F"\t" '{print NF}'`
$DEBUG $numberofcolumns
if [ $numberofcolumns -lt 3 ]
then
 $NOTE ${USAGE[general]}
 $NOTE ${USAGE[TAB]}
fi

columns=`head -1 $Csvfile|sed -e "s/\t/;/g"`
$NOTE $columns

if [ ! -e $Msgfile ]
then
 $NOTE ${USAGE[general]}
 $NOTE ${USAGE[Msgfile]}
 exit 4
fi

head ${Msgfile}
$NOTE $columns

if [ "x$4" == "x" ]
then
 $NOTE ${USAGE[para4]}
 read
fi

$DEBUG main
cd $outputfolder

$DEBUG create files according key
mv files $$ > /dev/null 2>&1
mkdir files $$ > /dev/null 2>&1
sed -e 's/\t/;/g' $Csvfile|
sed -e "s/\&/+++/g"	> $Csvfilesnew 
for i in `sed -e "1d" $Csvfilesnew|awk -F";" '{print $1}'` 
 do
  touch files/$i
 done

$DEBUG replace
cp $Msgfile $TEMPFILE
cd files
for i in *
 do
  $DEBUG $i
  cp $TEMPFILE $i
  z=0
  zeile=`grep $i ../$Csvfilesnew`
  IFS=";"
  column=( $zeile )

  for replace in $columns
   do
    sed -e "s|#$replace#|${column[$z]}|g" $i  > $TEMPFILE
    mv $TEMPFILE $i
    z=$((z+1))
   done 
   sed -i -e "s/+++/\&/g" $i
  done
 
rm $TEMPFILE > /dev/null 2>&1
